#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

remote="$1"
url="$2"

#####

# SETTINGS

username='<github_username>'
project='<project_name>'


z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
		:
	else
		if [ "$remote_sha" = $z40 ]
		then
			# New branch, examine all commits
			range="$local_sha"
		else
			# Update to existing branch, examine new commits
			range="$remote_sha..$local_sha"
		fi

		# Check for WIP commit
		commit=`git rev-list -n 1 --grep '^WIP' "$range"`
		if [ -n "$commit" ]
		then
			echo >&2 "Found WIP commit in $local_ref, not pushing"
			exit 1
		fi
	fi
done

########

# CREATE PULL REQUEST DESCRIPTION

current_branch=`git rev-parse --abbrev-ref HEAD`
IFS='-' read -r -a tmp_array <<< "$current_branch"

issue="${tmp_array[0]}-${tmp_array[1]}" 

body="[$issue](https://bifup.atlassian.net/browse/$issue)
--

#### Description

#### Add tests to check:
   - test returns 1

"
# CREATE PULL REQUEST TITLE

commit_message=`git log --pretty=format:%s -n1`
title="$commit_message"

open -a "Google Chrome" "https://github.com/$username/$project/compare/$current_branch?expand=1&body=$body&title=$title"

exit 0
